/**
 * snapCX - Address Validation APIs for commerce & retailers.
 * This set of API end points, provides real time address validations and corrections. Also do zipcode lookups etc. To invoke this API, you need to have your own private api key (aka user_key). You can always sign up for FREE plan to get user_key.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@snapcx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.snapcx.avs.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.snapcx.avs.client.model.RequestObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Header
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-03T19:15:39.720-05:00")
public class Header   {
  @JsonProperty("errorCode")
  private String errorCode = null;

  @JsonProperty("errorMessage")
  private String errorMessage = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("apiVersion")
  private String apiVersion = null;

  @JsonProperty("serverResponseTime")
  private String serverResponseTime = null;

  @JsonProperty("request")
  private RequestObject request = null;

  public Header errorCode(String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Error Code in case of any problem for this particular API call.
   * @return errorCode
  **/
  @ApiModelProperty(example = "null", value = "Error Code in case of any problem for this particular API call.")
  public String getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }

  public Header errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * Error Message in case of any problem. 
   * @return errorMessage
  **/
  @ApiModelProperty(example = "null", value = "Error Message in case of any problem. ")
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }

  public Header status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Two possible values, SUCCESS or FAIL.
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "Two possible values, SUCCESS or FAIL.")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Header apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * 
   * @return apiVersion
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public Header serverResponseTime(String serverResponseTime) {
    this.serverResponseTime = serverResponseTime;
    return this;
  }

   /**
   * 
   * @return serverResponseTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getServerResponseTime() {
    return serverResponseTime;
  }

  public void setServerResponseTime(String serverResponseTime) {
    this.serverResponseTime = serverResponseTime;
  }

  public Header request(RequestObject request) {
    this.request = request;
    return this;
  }

   /**
   * Get request
   * @return request
  **/
  @ApiModelProperty(example = "null", value = "")
  public RequestObject getRequest() {
    return request;
  }

  public void setRequest(RequestObject request) {
    this.request = request;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Header header = (Header) o;
    return Objects.equals(this.errorCode, header.errorCode) &&
        Objects.equals(this.errorMessage, header.errorMessage) &&
        Objects.equals(this.status, header.status) &&
        Objects.equals(this.apiVersion, header.apiVersion) &&
        Objects.equals(this.serverResponseTime, header.serverResponseTime) &&
        Objects.equals(this.request, header.request);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCode, errorMessage, status, apiVersion, serverResponseTime, request);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Header {\n");
    
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    serverResponseTime: ").append(toIndentedString(serverResponseTime)).append("\n");
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

