/**
 * snapCX - Address Validation APIs for commerce & retailers.
 * This set of API end points, provides real time address validations and corrections. Also do zipcode lookups etc. To invoke this API, you need to have your own private api key (aka user_key). You can always sign up for FREE plan to get user_key.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@snapcx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.snapcx.avs.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.snapcx.avs.client.model.Header;
import io.snapcx.avs.client.model.ZipRecordObj;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * InlineResponse2001
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-03T19:15:39.720-05:00")
public class InlineResponse2001   {
  @JsonProperty("header")
  private Header header = null;

  @JsonProperty("zipRecord")
  private List<ZipRecordObj> zipRecord = new ArrayList<ZipRecordObj>();

  public InlineResponse2001 header(Header header) {
    this.header = header;
    return this;
  }

   /**
   * Get header
   * @return header
  **/
  @ApiModelProperty(example = "null", value = "")
  public Header getHeader() {
    return header;
  }

  public void setHeader(Header header) {
    this.header = header;
  }

  public InlineResponse2001 zipRecord(List<ZipRecordObj> zipRecord) {
    this.zipRecord = zipRecord;
    return this;
  }

  public InlineResponse2001 addZipRecordItem(ZipRecordObj zipRecordItem) {
    this.zipRecord.add(zipRecordItem);
    return this;
  }

   /**
   * Get zipRecord
   * @return zipRecord
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ZipRecordObj> getZipRecord() {
    return zipRecord;
  }

  public void setZipRecord(List<ZipRecordObj> zipRecord) {
    this.zipRecord = zipRecord;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.header, inlineResponse2001.header) &&
        Objects.equals(this.zipRecord, inlineResponse2001.zipRecord);
  }

  @Override
  public int hashCode() {
    return Objects.hash(header, zipRecord);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    zipRecord: ").append(toIndentedString(zipRecord)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

