/**
 * snapCX - Address Validation APIs for commerce & retailers.
 * This set of API end points, provides real time address validations and corrections. Also do zipcode lookups etc. To invoke this API, you need to have your own private api key (aka user_key). You can always sign up for FREE plan to get user_key.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@snapcx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.snapcx.avs.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.snapcx.avs.client.model.AddressRecordObj;
import io.snapcx.avs.client.model.Header;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * InlineResponse200
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-03T19:15:39.720-05:00")
public class InlineResponse200   {
  @JsonProperty("header")
  private Header header = null;

  @JsonProperty("addressRecord")
  private List<AddressRecordObj> addressRecord = new ArrayList<AddressRecordObj>();

  public InlineResponse200 header(Header header) {
    this.header = header;
    return this;
  }

   /**
   * Get header
   * @return header
  **/
  @ApiModelProperty(example = "null", value = "")
  public Header getHeader() {
    return header;
  }

  public void setHeader(Header header) {
    this.header = header;
  }

  public InlineResponse200 addressRecord(List<AddressRecordObj> addressRecord) {
    this.addressRecord = addressRecord;
    return this;
  }

  public InlineResponse200 addAddressRecordItem(AddressRecordObj addressRecordItem) {
    this.addressRecord.add(addressRecordItem);
    return this;
  }

   /**
   * Get addressRecord
   * @return addressRecord
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AddressRecordObj> getAddressRecord() {
    return addressRecord;
  }

  public void setAddressRecord(List<AddressRecordObj> addressRecord) {
    this.addressRecord = addressRecord;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.header, inlineResponse200.header) &&
        Objects.equals(this.addressRecord, inlineResponse200.addressRecord);
  }

  @Override
  public int hashCode() {
    return Objects.hash(header, addressRecord);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    addressRecord: ").append(toIndentedString(addressRecord)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

