/**
 * snapCX - Address Validation APIs for commerce & retailers.
 * This set of API end points, provides real time address validations and corrections. Also do zipcode lookups etc. To invoke this API, you need to have your own private api key (aka user_key). You can always sign up for FREE plan to get user_key.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@snapcx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.snapcx.avs.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.snapcx.avs.client.model.ZipDetails;
import io.snapcx.avs.client.model.ZipSummary;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * ZipRecordObj
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-03T19:15:39.720-05:00")
public class ZipRecordObj   {
  @JsonProperty("zipSummary")
  private ZipSummary zipSummary = null;

  @JsonProperty("zipDetails")
  private List<ZipDetails> zipDetails = new ArrayList<ZipDetails>();

  public ZipRecordObj zipSummary(ZipSummary zipSummary) {
    this.zipSummary = zipSummary;
    return this;
  }

   /**
   * Get zipSummary
   * @return zipSummary
  **/
  @ApiModelProperty(example = "null", value = "")
  public ZipSummary getZipSummary() {
    return zipSummary;
  }

  public void setZipSummary(ZipSummary zipSummary) {
    this.zipSummary = zipSummary;
  }

  public ZipRecordObj zipDetails(List<ZipDetails> zipDetails) {
    this.zipDetails = zipDetails;
    return this;
  }

  public ZipRecordObj addZipDetailsItem(ZipDetails zipDetailsItem) {
    this.zipDetails.add(zipDetailsItem);
    return this;
  }

   /**
   * Get zipDetails
   * @return zipDetails
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ZipDetails> getZipDetails() {
    return zipDetails;
  }

  public void setZipDetails(List<ZipDetails> zipDetails) {
    this.zipDetails = zipDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ZipRecordObj zipRecordObj = (ZipRecordObj) o;
    return Objects.equals(this.zipSummary, zipRecordObj.zipSummary) &&
        Objects.equals(this.zipDetails, zipRecordObj.zipDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(zipSummary, zipDetails);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ZipRecordObj {\n");
    
    sb.append("    zipSummary: ").append(toIndentedString(zipSummary)).append("\n");
    sb.append("    zipDetails: ").append(toIndentedString(zipDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

